version: "3.9"
services:
  migrator:
    image: stepancons/crypto-news-migrator:dev
    container_name: migrator-dev
    networks:
      - dev
    volumes:
      - type: bind
        source: ./config.docker.dev.yaml
        target: /config.yaml
    environment:
      CONFIG: /config.yaml
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "migrator migrate up"
#  parser:
#    image: stepancons/crypto-news-parser:dev
#    container_name: parser-dev
#    networks:
#      - dev
#    volumes:
#      - type: bind
#        source: ./config.docker.dev.yaml
#        target: /config.yaml
#    environment:
#      CONFIG: /config.yaml
#    depends_on:
#      - migrator
#    restart: always
#    entrypoint: /bin/sh
#    command: -c "parser run"
  gpt:
    image: stepancons/crypto-news-gpt:dev
    container_name: gpt-dev
    networks:
      - dev
    volumes:
      - type: bind
        source: ./config.docker.dev.yaml
        target: /config.yaml
    environment:
      CONFIG: /config.yaml
    depends_on:
      - migrator
    restart: always
    entrypoint: /bin/sh
    command: -c "gpt run"
  telegram-bot:
    image: stepancons/crypto-news-telegram-bot:dev
    container_name: telegram-bot-dev
    networks:
      - dev
    volumes:
      - type: bind
        source: ./config.docker.dev.yaml
        target: /config.yaml
    environment:
      CONFIG: /config.yaml
    depends_on:
      - migrator
    restart: always
    entrypoint: /bin/sh
    command: -c "telegram-bot run"
  configuration-bot:
    image: stepancons/crypto-news-configuration-bot:dev
    container_name: configuration-bot
    networks:
      - dev
    volumes:
      - type: bind
        source: ./config.docker.dev.yaml
        target: /config.yaml
    environment:
      CONFIG: /config.yaml
    depends_on:
      - migrator
    restart: always
    entrypoint: /bin/sh
    command: -c "configuration-bot run"
  #  twitter-bot:
  #    image: stepancons/crypto-news-twitter-bot:latest
  #    container_name: twitter-bot-dev
  #    networks:
  #      - dev
  #    volumes:
  #      - type: bind
  #        source: ./config.docker.dev.yaml
  #        target: /config.yaml
  #    ports:
  #      - "8080:8080"
  #    environment:
  #      CONFIG: /config.yaml
  #    depends_on:
  #      - migrator
  #    restart: always
  #    entrypoint: /bin/sh
  #    command: -c "twitter-bot run"
  redis_db:
    image: redis:7-alpine
    container_name: redis_db-dev
    networks:
      - dev
    hostname: redis_db
    restart: always
    command: redis-server --save 20 1 --loglevel warning # --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  db:
    driver: local
  cache:
    driver: local

networks:
  dev:
    name: crypto_news_dev