version: "3.9"
services:
  migrator:
    image: stepancons/crypto-news-migrator:latest
    container_name: migrator
    networks:
      - default
    volumes:
      - type: bind
        source: ./config.docker.dev.yaml
        target: /config.yaml
    environment:
      CONFIG: /config.yaml
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "migrator migrate up"
  parser:
    image: stepancons/crypto-news-parser:latest
    container_name: parser
    networks:
      - default
    volumes:
      - type: bind
        source: ./config.docker.dev.yaml
        target: /config.yaml
    environment:
      CONFIG: /config.yaml
    depends_on:
      - migrator
    restart: always
    entrypoint: /bin/sh
    command: -c "parser run"
  gpt:
    image: stepancons/crypto-news-gpt:latest
    container_name: go-edge-gpt
    networks:
      - default
    volumes:
      - type: bind
        source: ./config.docker.dev.yaml
        target: /config.yaml
    environment:
      CONFIG: /config.yaml
    depends_on:
      - migrator
    restart: always
    entrypoint: /bin/sh
    command: -c "gpt run"
  telegram-bot:
    image: stepancons/crypto-news-telegram-bot:latest
    container_name: telegram-bot
    networks:
      - default
    volumes:
      - type: bind
        source: ./config.docker.dev.yaml
        target: /config.yaml
    environment:
      CONFIG: /config.yaml
    depends_on:
      - migrator
    restart: always
    entrypoint: /bin/sh
    command: -c "telegram-bot run"
#  twitter-bot:
#    image: stepancons/crypto-news-twitter-bot:latest
#    container_name: twitter-bot
#    networks:
#      - default
#    volumes:
#      - type: bind
#        source: ./config.docker.dev.yaml
#        target: /config.yaml
#    ports:
#      - "8080:8080"
#    environment:
#      CONFIG: /config.yaml
#    depends_on:
#      - migrator
#    restart: always
#    entrypoint: /bin/sh
#    command: -c "twitter-bot run"
  redis_db:
    image: redis:7-alpine
    hostname: redis_db
    restart: always
    command: redis-server --save 20 1 --loglevel warning # --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  db:
    driver: local
  cache:
    driver: local